### ISSUE TITLE
where to look for "Restricted File" .git/objects/ae/b3cc1b883bf023a2c07c16f05df36a457eef4b ?

### ISSUE THREAD

**Issue by KseniaZhe** [KseniaZhe/stylish-beets#1]
I have an issue with the stylish-beets project: 
Markbot is convinced that I have a file with this name (see lower), which is not true. 

**Naming & Files** - **Restricted Files**
`.git/objects/ae/b3cc1b883bf023a2c07c16f05df36a457eef4b`:
**shouldn't be inside the repository.**

I checked all the files in the folder stylish-beets on my computer and the repository on GitHub,
and I haven't found this file.

Can you give me a hint where to look for this intruder?
Thank you

@thomasjbradley

**Comment by thomasjbradley** [comment]
Sorry, that's small bug in Markbot that I've recently fixed.

Download and install this new version and the problem should disappear:
https://www.dropbox.com/s/w7y5wxp7mtcylkd/Install%20Markbot.dmg?dl=1

**Comment by KseniaZhe** [comment]
Perfect! Thank you very much!
Hurray! Assignment submitted!)
